### PR TITLE
Fix a couple of warnings

### PR DESCRIPTION
**Pull request by SquidDev**
AKA the, "oh goodness, I broke everything pr".

> It does not add unneccessary complexity or stylistic changes to the code, especially where functionality is not being changed.

Yes. This falls at the first hurdle, however I do think it is worth considering. This is the result of me cranking up Java's and IntelliJ's warnings to 11 and fixing most of what they sprung at me. A rough synopsis of what has changed in this PR:

 - Add `@NonNull` and `@Nullable` annotations to the public API, as well as all overriding methods.
 - Replace numeric `for` loops and `while` loops with `for` iterator loops.
 - Make a lot more code use generics. As of Minecraft 1.8.9, many Minecraft methods work with generics, meaning we can get rid of a lot of unchecked code and ugly casts.
 - Mark deprecated methods with `@Deprecated` and fix all other usage of deprecated methods.
 - Make all the license text a block comment instead of Javadoc.
 - Make many unmodified fields final - especially when they are `synchronized` on.

I've tried to keep formatting changes to a minimum, though it may also be worth running a source formatter over some of the code. This would help make it clearer to contributors what style is preferred, and so help keep the source consistent.

### CODE REVIEW

**Comment by dan200** [comment]
No worries, I count fixing compile warnings as bug fixes! I'll merge this
after I merge some of the other big pr's to cut down on conflict hell

**Comment by SquidDev** [comment]
After much aggressive rebasing, merged commits should now be resolved.

> I'll merge this after I merge some of the other big pr's to cut down on conflict hell

Yeah. I realise this does touch a fair amount of the code, and so will cause some issues. I'm happy for this to be merged before any of my other PRs - I don't really mind resolving merge conflicts on my end. I don't know what other PR authors think though.

**Comment by dan200** [comment]
Looking to merge this one next. Want the chance to rebase against the latest merge PR's first? Or is it good to go?

**Comment by SquidDev** [comment]
I think it's good to go.

**Comment by dan200** [comment]
Gonna take your word for it then :) THere's far too much to review by hand :p

**Comment by SquidDev** [comment]
Great. Thank you! ❤

**Pull request merged**
