### PR TITLE
Better Style of Syntax error

### PR DESCRIPTION
**Pull request by Wilma456**
I think the new looks more like native LUA.

### CODE REVIEW

**Comment by SquidDev** [comment]
You don't need the `-1` on the `sub` calls - Lua will default to the end of the string.

Worth noting that this is also fixed by #163 (/me does puppy eyes at @dan200).

**Comment by SquidDev** [comment]
It's also worth noting that `name` can be nil, which will result in `lua` exiting.

**Comment by Wilma456** [comment]
@dan200  Have you any example who name is nil, so I can look how to fix this?

**Comment by SquidDev** [comment]
@Wilma456 You're allowed to use `load` - something like `load("return 1")` is legal. Trying to do `load("1")` crashes with `bios.lua:22: attempt to get length of nil`.

**Comment by Wilma456** [comment]
@SquidDev Should be fixed now

**Comment by SquidDev** [comment]
@Wilma456 Trying `load("x")` produces `nilg"]: '=' expected` on my machine, which is far from ideal :). 

> From my testing, `return false, err:sub(14)` is sufficient to strip the `bios.lua` element off. Just wondering why you went for the current method rather than this?

**Comment by Wilma456** [comment]
`if err == nil then  return` should protect from this. Crazy.

**Comment by Wojbie** [comment]
Why did you put read char limit into this PR?

**Comment by Wilma456** [comment]
@Wojbie Sorry, this was in the same file and I had not see this. It is now removed.

**Comment by Wojbie** [comment]
You forgot to push.

**Comment by Wilma456** [comment]
No. In my Repository it is fixed. https://github.com/Wilma456/ComputerCraft-1/blob/syntaxerr/src/main/resources/assets/computercraft/lua/bios.lua But is not shown here. Maybe it's a Bug of Github. I wait a few hours.

**Comment by SquidDev** [comment]
> `if err == nil then return` should protect from this. Crazy.

That won't do anything: `load` should never return a nil error message so that check is redundant. The issue is that your `:sub` code is invalid.

> From my testing, `return false, err:sub(14)` is sufficient to strip the `bios.lua` element off. Just wondering why you went for the current method rather than this?

**Comment by dan200** [comment]
This is very hacky

**Pull request closed without merging**
