### PR TITLE
Port to 1.11 [Not Ready For Merge]

### PR DESCRIPTION
**Pull request by TheCodedOne**
This PR is only partially complete, there are quite a few issues I still need to solve with it, I've opened it as a PR so people can comment on issues they see with the code as they come up instead of a giant mash of stuff.

### CODE REVIEW

**Comment by SquidDev** [comment]
Firstly, on the topic of 1.11.2: I'm not sure ComputerCraft should target 1.11.2 right away. 1.10.2 is still the "main" version, so it seems sensible to target that. A possible alternative would be to have a 1.11.2 branch and routinely rebase it/merge 1.10.2 onto it.

Secondly, there are a couple of things here which might be worth splitting into a separate PR and merging into the 1.10.2 version (well, we're currently targeting 1.9.4, but I'll ignore that 😄). The key things which stick out are item capabilities and using Forge's new registry system.

Anyways, onto this PR.
 - The mod won't actually load as the mod id is still capitalised. If you change it where required (`ComputerCraft`, `ComputerCraftProxyCommon.ForgeHandler#onConfigChanged`, `GuiConfigCC`, `mcmod.info`) it should load.
 - Many resources are still upper case. I presume you just forgot to copy this out of the Computality repo. This means you get a lot of missing model errors.
 - I notice you use `NonNullList.create` inside the recipes. It might be more efficeint to use `NonNullList.withSize` and `NonNullList.set` instead.

Also, a couple of issues I had when porting it via Unborked. I can't say how relevant they are, as it's internals were rather different.
 - `turtle_inventory` and `disk_eject` events were not fired when using moving items in the GUI. I cannot remember if this happened all the time, or just when shift-clicking items. I'm not sure if this is an issue when using capabilities.

Anyway, good job!

**Comment by TheCodedOne** [comment]
yeah, the modid and resource names are actually done in my local i just didn't push them for some reason, they'll be my next push

**Comment by TheCodedOne** [comment]
on the note of 1.10 instead of 1.11, it might be wise to do it but, 1.11 is becoming the major version with most mods at least on their way over, albeit extremely slowly

**Comment by TheCodedOne** [comment]
worth noting, i am aware that the turtle models do not work in inventory, i'm not 100% sure whats causing that yet

**Comment by TheCodedOne** [comment]
and pressed the wrong button for comment :/

**Comment by SquidDev** [comment]
`termfront.png` instead of `termfont.png` 😛.

**Comment by TheCodedOne** [comment]
no idea why i called it `termfront`, derp

**Comment by SquidDev** [comment]
A couple of other things:

 - The creative group now needs a language key (`itemGroup.ComputerCraft`)
 - [Config change listener](https://github.com/TheCodedOne/ComputerCraft/blob/master/src/main/java/dan200/computercraft/shared/proxy/ComputerCraftProxyCommon.java#L678) still uses the upper case mod id.
 - Crash when removing an item from a disk drive:

```
java.lang.NullPointerException: Updating screen events
        at net.minecraft.item.ItemStack.areItemStacksEqual(ItemStack.java:376)
        at net.minecraftforge.items.ItemStackHandler.setStackInSlot(ItemStackHandler.java:59)
        at dan200.computercraft.shared.peripheral.diskdrive.TileDiskDrive.setInventorySlotContents(TileDiskDrive.java:258)
        at dan200.computercraft.shared.peripheral.diskdrive.TileDiskDrive.decrStackSize(TileDiskDrive.java:237)
        at net.minecraft.inventory.Slot.decrStackSize(Slot.java:98)
        at net.minecraft.inventory.Container.slotClick(Container.java:296)
```

 - NPE placing turtle:

```
Caused by: java.lang.NullPointerException
        at net.minecraft.item.ItemStack.areItemStacksEqual(ItemStack.java:376) ~[ItemStack.class:?]
        at dan200.computercraft.shared.turtle.blocks.TileTurtle.markDirty(TileTurtle.java:575) ~[TileTurtle.class:?]
        at dan200.computercraft.shared.common.TileGeneric.updateBlock(TileGeneric.java:68) ~[TileGeneric.class:?]
        at dan200.computercraft.shared.computer.blocks.TileComputerBase.createServerComputer(TileComputerBase.java:441) ~[TileComputerBase.class:?]
        at dan200.computercraft.shared.computer.blocks.TileComputerBase.update(TileComputerBase.java:204) ~[TileComputerBase.class:?]
        at dan200.computercraft.shared.turtle.blocks.TileTurtle.update(TileTurtle.java:258) ~[TileTurtle.class:?]
```

Sorry for all the reports 😦. I realise you may be aware of some of these already, and that this is a WIP.

**Comment by TheCodedOne** [comment]
yeah, im aware of the turtle thing and the disk drive, any issues you find you should put here because even if i do know about them, it reminds me to fix them

**Comment by SquidDev** [comment]
@TheCodedOne Wondering if you'd made any progress on this? #224 got merged, which should mean you don't have to lower case any model names any more (well, block states/names still need changing). I [had a prod](https://github.com/SquidDev-CC/ComputerCraft/commit/5d67fecb3617fa0c4d1ccf66d180589f5a42589b) at porting Unborked's patches to CC, so feel free to reference that.

**Comment by dan200** [comment]
Have you abandoned your port @TheCodedOne? If so, I'll close this PR. @SquidDev has produced his own PR for the 1.11 update, and it's much less out of date with the changes that have happened in the interim.

**Comment by TheCodedOne** [comment]
@dan200 i havent, i just havent gotten round to pushing changes recently

**Comment by dan200** [comment]
Closing this as it's hopelessly out of date and SquidDevs pr does the same thing better

**Pull request closed without merging**
