### PR TITLE
Removed the ~= nil checks from the bios checks. This will allow false…

### PR DESCRIPTION
**Pull request by Scoopta**
Removed the ~= nil checks from the bios checks. This will allow false to be used in place of nil. I make this change primarily because I have code that submits arguments with table.unpack and used false instead of nil. All of that code is now broken. Apparently my text editor also stripped extra spaces from the ends of stuff.

### CODE REVIEW

**Comment by Wojbie** [comment]
Well first thing is. Can you explain exactly how this change is important for CC other then not making you rewrite your code?

And for second qutestion. - Why are you using false instead of nil?

**Comment by Scoopta** [comment]
I explained why I'm using false. I need to use tables to pack and pass variables. It's considerably easier than varargs in this particular segment of code and I can't put nil into a table. As far as why it's important? It shouldn't affect anything. It shouldn't break anything and the checks should behave identically to the way they do now. The only difference is you can pass false or nil instead of just nil. It's not particularly important but at the same time I don't really see a reason not to pull it.

**Comment by Wojbie** [comment]
@Scoopta 
This about the meaning of values. 
When function expects a string and gets a boolean that means something went wrong. It got value it did not expect.
When function expects string and you gave it a nil that means you wanted to give it “absence of a value". This makes function assume default functionality there or error if there is no default functionality for that part.
I hope this explains my stance on this issue, I do believe even if this " It shouldn't break anything" its still a bad programing practice and not something we should be following.
Unless you have any other reasoning for this PR other then " I can't put nil into a table" then i will say its a bad code.
As for putting nils in table? `table.pack("One","Two",nil,"4")` will give you table with nil in 3th positions and total amount of arguments passed to in under `n` key. You could try using this method to construct your tables.

**Comment by Scoopta** [comment]
@Wojbie that does not even come close to working.
`test = table.pack(1, 2, nil, 4)
table.unpack(test)`
I need that to be 1, 2, nil, 4...I get 1, 2. That's my point. I get your point that they mean two different things but nil is literally the only value that can be passed to mean "I don't want to replace." If false isn't any good then allow an empty string to mean "do not replace." As it is space can be used for replacing with nothing. I need to do read(table.unpack(_table)). I don't know how many arguments are given to me and they're not passed in a way where varargs would work and there's no real way to make varargs work.

**Comment by Wojbie** [comment]
@Scoopta You need to use 2nd and 3th argument of unpack. By default it prints until first nil but you can tell it to print until specified number. Like key n that is given to you by table.pack function
``
a = table.pack(1, 2, nil, 4)
 print(table.unpack(a,1,a.n))
``
Does exactly what you are trying to achieve.

**Comment by Scoopta** [comment]
@Wojbie That doesn't work in old versions of CC. Ugh version checking...oh well...it seems to work in newer versions. Chances are my code will break on some version somewhere because of this but whatever. I understand the false argument but that's still way cludgier than "" IMO but I guess you won't change your mind. I think I'mma go do my own read and try to remove my dependency on bios all together.

**Comment by BombBloke** [comment]
"a.n or table.maxn(a)" should work under any version.

**Comment by Scoopta** [comment]
@BombBloke I wasn't referring to a.n. I was referring to table.unpack. In the current official build table.unpack always stops at nil no matter what I specify. As I said...it doesn't really matter. I'm just not going to use read.

**Comment by SquidDev** [comment]
@Scoopta `table.unpack` seems to work fine on 1.79. The only issue is that `print` stops on the first `nil` element.

```lua
local x = table.pack(1, 2, nil, 3)
local a, b, c, d = table.unpack(x, 1, x.n)
assert(d == 3)
```

Worth noting that `table.pack` was broken on earlier versions of the mod (pre 1.78), so you might want to include the patch in #90.

**Comment by Scoopta** [comment]
@SquidDev ...that would explain...a lot. Well I'm already part way through the change anyway and one of the long term goals is to eventually remove bios as a dependency of this project anyway so it's not that big of a deal. I was probably going to have to do this anyway.

**Comment by Scoopta** [comment]
@SquidDev I still don't personally see a problem with passing it false instead of nil. I only half see it as a problem of bad practice. In lua they more or less "mean" the same. I get the semantics but in an if statement there's no difference. That being said I'd be lying if I said I don't do ~= nil in my own code although that's really more because I come from a background of languages where nil/null is not false and cannot be treated as such and so it's just habit.

**Comment by SquidDev** [comment]
>  I get the semantics but in an if statement there's no difference.

Whilst `nil` is falsey, it isn't the same as *false*. `nil` represents the absence of a value meanwhile `false` is a value. This is useful if you're trying to emulate default arguments in a function:

```lua
local function doTheThing(doIt)
    if doIt == nil then -- Nothing was given, use true as the default.
        doIt = true
    elseif type(doIt) ~= "boolean" then
        error("expected boolean", 2)
    end
    -- Do the thing!
end
``` 

> I come from a background of languages where nil/null is not false and cannot be treated as such and so it's just habit.

I'm not convinced that `nil` should be falsey, but then I'm a strong typing fanatic, so I'd want anything which isn't a boolean to produce a runtime error :). At least it isn't Javascript where you have `null`, `undefined` and `false`.

I think the killer argument here is that treating `false` equivalent to `nil` defines convention - the Lua standard library treats them differently. For instance, compare these two calls:

```lua
table.concat({"x", "y"}, nil) -- xy
table.concat({"x", "y"}, false) -- bad argument #2 to 'concat' (string expected, got boolean)
```

Whilst using `false` *may* work on *some* libraries, you're eventually going to hit problems somewhere else, so it's just better to do it "the right way".

**Pull request closed without merging**
