### PR TITLE
Add fileextension for Paint

### PR DESCRIPTION
**Pull request by Wilma456**
I added a file extension for Paint: mcpi. It stands for "**Minecraft** **Computercraft** **Paint** **Image**". I have tried to find a extension that no other program use. If the user call paint, with a filename, who has no extension and this file does not exists, paint will add .mcpi to the filename. If you know better extension, who no other program use, let me know.

### CODE REVIEW

**Comment by SquidDev** [comment]
From what I remember, the community has generally used `.nfp` as a file extension, in homage of [NPaintPro](http://www.computercraft.info/forums2/index.php?/topic/5029-145-npaintpro/). I feel it would probably be worth sticking with it.

You might also want to just use the same check as `edit.lua` does, which looks a little neater:

```lua
if not fs.exists( sPath ) and not string.find( sPath, "%." ) then
	sPath = sPath .. ".nfp"
end
```

**Comment by Wilma456** [comment]
Don't know, that a extension already exits. I have change it.

**Comment by dan200** [comment]
Does anybody know if "paint" images are 100% cross-compatible with NPaintPro images?

**Comment by SquidDev** [comment]
I had a prod at the code and it looks like it. NPaintPro also supports another format (nft) which isn't compatible, but we don't need to worry about that.

I don't know if it would be worth adding a setting, like in #278?

**Comment by dan200** [comment]
Doesn't seem necessary, but if one is added, i would like it to match the design I proposed in my latest comment over there!

**Comment by Wilma456** [comment]
I will add a extension for it, when you merge my other PR, because I don't want conflict.

**Comment by dan200** [comment]
The other PR is now merged. Please ensure your changes here match the style of that one *exactly* so we don't have to waste time going back and forth again.

**Comment by Wilma456** [comment]
@dan200  Now done!

**Comment by dan200** [comment]
Perfect

**Pull request merged**
