### PR TITLE
Small cleanup in ComboMount

### PR DESCRIPTION
**Pull request by Lignum**
I changed the constructor to take varargs instead of an array and changed all the loops to iterate forwards, so that the mount parts are prioritised in the order they are passed to the constructor, not in the reverse order.

### CODE REVIEW

**Comment by SquidDev** [comment]
If you're doing this, you should reverse the order mounts are passed in when constructing this - otherwise you won't be able to override rom files with resource packs.

**Comment by Lignum** [comment]
Hm, I hate to give up the intuition here, so I came up with this compromise, which I hope is an agreeable solution.

**Comment by SquidDev** [comment]
An alternative solution woild be to reverse the lookup order in getResourceMount - so it lists resource packs, debug and then the mod jar. This way resource packs are loaded in alphabetical order, which might be more intuitive.

**Comment by dan200** [comment]
Iterating in reverse order is very much deliberate: the whole point is that later mounts can override files in earlier mounts.

**Comment by Lignum** [comment]
Oh, well, in that case, I'm closing this PR. I don't deem the varargs constructor important enough to be in need of merging.

**Pull request closed without merging**
