### PR TITLE
Modify logic behind ... and more in file path.

### PR DESCRIPTION
**Pull request by Wojbie**
Changes all equal or longer then 3 multidots setups to be treated as .
This removes other potentially dangerous situations and brings it closer to windows in how it treats said dots. This makes sure that even on systems that have wierd magic meanings to ... and onward CC will work with predictable path no matter the system.

This fixed the bugs expressed in #35 , http://www.computercraft.info/forums2/index.php?/topic/16882-computercraft-beta-versions-bug-reports/page__st__40__p__213941#entry213941 and http://www.computercraft.info/forums2/index.php?/topic/28870-command-crashes-computer/

### CODE REVIEW

**Comment by dan200** [comment]
This is a good change, but I don't like the performance hit of compiling a regular expression several times on every path operation. Precompile the pattern!

**Comment by Wojbie** [comment]
Hopefully compiling it once for each path operation is ok? I completely did not think about that for loop there for some reason.
Anyhow requested changes implemented.

**Comment by dan200** [comment]
Maybe make the pattern a static class member?

**Comment by Wojbie** [comment]
I was not sure what was a standard for placement of  static class member. Hope this is correct way?
Anyhow requested change implemented.

**Pull request merged**
