### PR TITLE
Switch lua.lua to use extutils.pagedPrint() for Tables

### PR DESCRIPTION
**Pull request by JakobDev**
With this PR lua.lua can how the full table, if the table is bigger than your Screen.

### CODE REVIEW

**Comment by SquidDev** [comment]
I feel we'd have to improve `pagedPrint` before doing this, maybe [something like this](https://github.com/dan200/ComputerCraft/issues/212#issuecomment-299712364). Otherwise you're going to be pressing keys a long time for big tables.

It might also be worth creating a modified serialise function, which can handle recursive structures and functions.

**Comment by Wilma456** [comment]
Sorry for closing

**Comment by apemanzilla** [comment]
Eh, I'm not really sure if this should be the default behavior. This is a REPL, you can always call `textutils.pagedPrint` yourself.

**Comment by lupus590** [comment]
Perhaps have this as an option in settings?

**Comment by BombBloke** [comment]
I'd rather it be the default behaviour, personally. It's hard to think of cases where I'd ever want part of a displayed table to be immediately hidden out the top of my screen (it's not like we can scroll back up), and if I *do* decide it'll take too long to scroll through a complete table, I can always just terminate the textutils call.

**Pull request closed without merging**
