### PR TITLE
Fix ComputerCraftAPI.getWirelessNetwork() failing

### PR DESCRIPTION
**Pull request by SquidDev**
I've got to admit, it is super embarrassing that a) I didn't notice this when testing and b) no one else has noticed until now. Sorry.

### CODE REVIEW

**Comment by xAnavrins** [comment]
What effect did this have on gameplay?

**Comment by SquidDev** [comment]
There's no direct effect on gameplay. It prevented some cross mod integration though.

**Comment by Vexatos** [comment]
Speciifcally, it makes the entire new wireless network API useless.

**Comment by SquidDev** [comment]
Thanks!

**Pull request merged**
