### PR TITLE
Enable Syntaxhighlight on normal Computers in edit

### PR DESCRIPTION
**Pull request by Wilma456**
edit

### CODE REVIEW

**Comment by SquidDev** [comment]
I like this in principle, but I'm really not sure this works with the default palette. I wonder if #307 is sufficient, that way people can configure the palette and colours themselves.

**Comment by Wilma456** [comment]
I don't think that #307 will be merged in the next time. What do you mean with "default palette"? This are the default colours. I don't run  setPalleteColor().

**Comment by SquidDev** [comment]
> I don't think that #307 will be merged in the next time.

It's not really a measure of when it'll be merged, rather if it'll be merged. There's no point duplicating work just because one PR will be merged sooner than another.

> What do you mean with "default palette"? This are the default colours. I don't run setPalleteColor().

I know, and I don't think the colours in the screenshot work. Strings are rather hard to read for instance. *However* if someone changed the palette a little, they might find a colour/palette combination that worked for them.

**Comment by dan200** [comment]
No thanks.

**Pull request closed without merging**
