### PR TITLE
Add virtual peripherals

### PR DESCRIPTION
**Pull request by Wilma456**
I had add virtual peripherals. Examples for Usage:
-Use peripherals over remote
-Make a virtual speaker for a command computer, that use the command API
-Read the screen with a virtual monitor, without overwrite the term API
That just 3 examples. Maybe you have more.

### CODE REVIEW

**Comment by Wojbie** [comment]
Honestly this sounds like something people put in API part of CC forums.
As this whole thing is pure Lua code and can be easily implemented using end user code i don't really see point of filling the environment with extra functions with rare use cases.

**Comment by Wilma456** [comment]
But you have to overwrite the API to do this and I think overwriting the API is not a good coding style, but you have to do this too much in CC actually.

**Comment by Wojbie** [comment]
Every single program that adds functionality to existing system has to overwrite it.
I just simply don't see usability of this feature for a new player and advanced player can easily implement his own variation of this on its own.

**Comment by Wilma456** [comment]
I just want, that overwriting APIs is no longer needed in many usecases.

**Comment by dan200** [comment]
As people have said, this doesn't seem a good fit for inclusion in CC: it complicates the peripheral API for newcomers, and provides nothing an advanced user couldn't add themselves.

This is better off as a user-distributed library, which luckily are very easy to distribute now we have require :)

**Comment by CoolMan119** [comment]
If you really want that you can make the jar with your PR but it won't be on the CC repo.

**Comment by dan200** [comment]
or just make an API and release it as a resource pack or a pastebin, as this is only a lua change

**Pull request closed without merging**
