### PR TITLE
move treasure disks to rom/programs/legacy

### PR DESCRIPTION
**Pull request by lupus590**

### CODE REVIEW

**Comment by dan200** [comment]
why?

**Comment by lupus590** [comment]
Just in case people wanted them, or because I could. I just thought of the idea and managed to implement it before thinking otherwise.

**Comment by dan200** [comment]
Treasure disks haven't been removed from the mod.

**Comment by lupus590** [comment]
>Merged. Though Treasure Disks have been deprecated and *disabled by default for a few versions now* and I may end up just removing them altogether.
#279

**Comment by dan200** [comment]
Correct. They're disabled by default, not removed. Anyone who wants these
programs can just enable disks again.

**Pull request closed without merging**
