### PR TITLE
Fix Bug with peripheral.find()

### PR DESCRIPTION
**Pull request by BombBloke**
Since #315 peripheral.find() doesn't work. This PR fix this.

### CODE REVIEW

**Comment by BombBloke** [comment]
I've also skimmed through all the other files #315 affected, and as far as I can see these are the only two negatively affected.

**Comment by Wojbie** [comment]
Ok this time peripheral.find() is fixed. For sure!

**Comment by Wilma456** [comment]
In #320 I only want to made edit work. I did not see this. Sorry.

**Comment by Wojbie** [comment]
Hey don't worry @Wilma456. Whole point of open source is that many eyes beat pair of eyes.

**Comment by SquidDev** [comment]
If anyone should be apologising it should be me - I was the one who wrote the code. Sorry!

**Pull request merged**
