### PR TITLE
Switch wget to use binary mode.

### PR DESCRIPTION
**Pull request by Wojbie**
Allows wget to download all types of files not only text ones.

This makes use of changes SquidDev made to http and fs to make wget get all types files correctly.

### CODE REVIEW

**Comment by xAnavrins** [comment]
Have you tested this, you sure it won't just save the first byte?

**Comment by Wojbie** [comment]
Yes tested and retested. There were changes to http api and fs api in #238 that make this work.

**Comment by Wojbie** [comment]
Opse.

**Comment by SquidDev** [comment]
@xAnavrins Binary handles now have a `readAll` method, which this will use. The `write` method now accepts a string too, which will be saved as its byte representation.

**Pull request merged**
