### PR TITLE
Localize ComputerCraft for es_ES

### PR DESCRIPTION
**Pull request by daelvn**
es_ES: Español de España (Castellano)
I created a .lang file for es_ES, it's my native language, so I thought I could do it.
Although untested, it should work fine, just as en_US works.

### CODE REVIEW

**Comment by Wilma456** [comment]
dan200 doesn't want other languages than English in the main mod. See #5

**Comment by SquidDev** [comment]
@Wilma456 Dan's changed his mind on that (https://github.com/dan200/ComputerCraft/issues/294#issuecomment-328358222), so we're all good.

> I would probably accept PR's for built in localisations now.

**Comment by Wilma456** [comment]
@SquidDev Thank you. I have not see this. If dan200 accept this PR, I will make a PR for German.

**Comment by scollovati** [comment]
Thank you! If this PR is accepted, I can create a PR for Italian translation.

**Comment by thatcraniumguy** [comment]
Can one of the admins verify this patch?

**Pull request closed without merging**
