### PR TITLE
Add /apis to package.path

### PR DESCRIPTION
**Pull request by Wilma456**
With this PR we had a standard folder for apis.

### CODE REVIEW

**Comment by CrazedProgrammer** [comment]
Having a hardcoded path for global APIs is not only inextensible but also a bad practice.

**Comment by lupus590** [comment]
could the path be loaded from settings?

**Comment by apemanzilla** [comment]
@lupus590 For consistency I'd say it should be left the way it is, the way `shell.path` works.

**Comment by SquidDev** [comment]
@apemanzilla I agree, though worth noting that the include path is entirely hard coded. It would be nice to have a `shell.setRequirePath` or something.

**Comment by apemanzilla** [comment]
Can't you just do `package.path = ...`?

**Comment by SquidDev** [comment]
@apemanzilla Yes, but only in the main program - as it is a new instance every program run, changing it in startup will not help. That being said, I can see potential for people confusing the two methods, so maybe it is something which should be avoided.

**Comment by dan200** [comment]
Nope. APIs and libraries are different things

**Pull request closed without merging**
