### PR TITLE
Add equip and unequip for Pocket Computers

### PR DESCRIPTION
**Pull request by Wilma456**
We had this Programs for Turtles and now can Pocket Computers also use equip, so I add this programs for Pocket Computers.

The User shouldn't notice a different between equip for Pocket and equip for Turtles.

### CODE REVIEW

**Comment by SquidDev** [comment]
It might be worth also having a side argument, even if it is limited to "back". I'm planning to create a PR implementing #270 at some point, which will introduce another side.

**Comment by Wilma456** [comment]
I will wait for your PR

**Comment by dan200** [comment]
Merged. @SquidDev feel free to ammend this program in your pr

**Comment by hugeblank** [comment]
@SquidDev Can I ask how the progress of the side argument is coming? I plan on making a sonar application that sends out a sound that gets faster the closer you get to another computer. While that's possible with what is already merged, just by equipping and unequipping, it would be much easier to just have both peripherals on the computer. :P

**Comment by SquidDev** [comment]
@hugeblank I'm wanting to get #314/#331 fixed before doing any more work on pocket computers. However, I'm not sure which of the approaches outlined in the latter issue is the "best" one, and therefore am waiting for Dan to have a little bit more free time so that can be discussed.

**Comment by hugeblank** [comment]
@SquidDev Absolutely understandable. Bug squashing before you add a feature that will consequently add more.

**Pull request merged**
